### ISSUE TITLE
Twisted OSError: [Errno 98] Address already in use 

### ISSUE THREAD

**Issue by Arconapalus** [thinkst/opencanary#105]
I started tinkering around this and have opencanary running on raspbian pi, however I came across this.
I have research this and nothing comes up beside what is in the issue regarding the upgrade.

```
2020-10-14T15:55:34-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.10.0 (/home/pi/overwatch/opcan/bin/python3 3.7.3) starting up.
2020-10-14T15:55:34-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-10-14T15:55:34-0500 [stderr#error] Traceback (most recent call last):
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/internet/tcp.py", line 1361, in startListening
2020-10-14T15:55:34-0500 [stderr#error]     skt.bind(addr)
2020-10-14T15:55:34-0500 [stderr#error] OSError: [Errno 98] Address already in use
2020-10-14T15:55:34-0500 [stderr#error] During handling of the above exception, another exception occurred:
2020-10-14T15:55:34-0500 [stderr#error] Traceback (most recent call last):
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/bin/twistd", line 10, in <module>
2020-10-14T15:55:34-0500 [stderr#error]     sys.exit(run())
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 31, in run
2020-10-14T15:55:34-0500 [stderr#error]     app.run(runApp, ServerOptions)
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/application/app.py", line 674, in run
2020-10-14T15:55:34-0500 [stderr#error]     runApp(config)
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
2020-10-14T15:55:34-0500 [stderr#error]     runner.run()
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/application/app.py", line 385, in run
2020-10-14T15:55:34-0500 [stderr#error]     self.postApplication()
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/scripts/_twistd_unix.py", line 254, in postApplication
2020-10-14T15:55:34-0500 [stderr#error]     self.startApplication(self.application)
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/scripts/_twistd_unix.py", line 442, in startApplication
2020-10-14T15:55:34-0500 [stderr#error]     service.IService(application).privilegedStartService()
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/application/service.py", line 283, in privilegedStartService
2020-10-14T15:55:34-0500 [stderr#error]     service.privilegedStartService()
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/application/internet.py", line 114, in privilegedStartService
2020-10-14T15:55:34-0500 [stderr#error]     self._port = self._getPort()
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/application/internet.py", line 142, in _getPort
2020-10-14T15:55:34-0500 [stderr#error]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2020-10-14T15:55:34-0500 [stderr#error]     p.startListening()
2020-10-14T15:55:34-0500 [stderr#error]   File "/home/pi/overwatch/opcan/lib/python3.7/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2020-10-14T15:55:34-0500 [stderr#error]     raise CannotListenError(self.interface, self.port, le)
2020-10-14T15:55:34-0500 [stderr#error] twisted.internet.error.CannotListenError: Couldn't listen on any:21: [Errno 98] Address already in use.
```

**Comment by jayjb** [comment]
Hi @Arconapalus,

Just having a quick look, that error message usually means that the host OS that you are running your OpenCanary on, has something already using that port. If it is port 21, it is likely some FTP service. 

What you mind giving me some more information about your setup? What are you running Opencanary on? Which OS? 

You could also quickly investigate which process is using port 21 using `netstat <options> | grep 21`. I haven't specified the `<options>` because `netstat` differs slightly between different systems.

**Comment by Arconapalus** [comment]
In my development, I have installed this on raspberry pi3 raspbian using python3 and pip3 and created a python venv to install opencanary. I went back in a couple of days later to check to status and I think it was currently running and then when I ran the 
```opencanaryd --dev``` I was double-checking that opencanary was still running after I close the venv and logged off. Pretty new to python venv. 

I was thinking that twistd is already running and then re-running again. 
I ran the above command ```netstat -tulpn | grep 21```

tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      2343/python3

Then I also ran ```sudo ss -tulpn``` and output 
tcp    LISTEN  0       50               0.0.0.0:21             0.0.0.0:*      users:(("twistd",pid=2343,fd=11))

**Comment by jayjb** [comment]
Hi @Arconapalus,

Sorry for the delayed response. Am I to understand that you tried running the `opencanaryd --dev` whilst another version of it was running? Because that would explain why you are seeing that that port is in use.

**Comment by Arconapalus** [comment]
No worries, I'm pretty new to the python virtual env and assumed for some reason that when I exited out of the env that it stops the process. Apparently, it did not.

Thank you again for your expertise

**Comment by jayjb** [comment]
Hi @Arconapalus,

Absolutely not a problem at all. Please let me know if you hit any issues and im sure we will get them sorted! Always happy to help.

Good luck

**Comment by H20-Jenish** [comment]
### Hello there, 

I am having a problem working with SSL strip and I saw this post somewhere close to my issue. please guide me through. how I can fix this. I have tried other methods but nothing works in my favour. 

┌──(root㉿Security)-[~]
└─# sslstrip -l 8080
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 1346, in startListening
    skt.bind(addr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/sslstrip", line 112, in <module>
    main(sys.argv[1:])
  File "/usr/bin/sslstrip", line 104, in main
    reactor.listenTCP(int(listenPort), strippingFactory)
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 364, in listenTCP
    p.startListening()
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 1348, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8080: [Errno 98] Address already in use.

**This is my listening port:** - 

┌──(root㉿Security)-[~]
└─# netstat -tlpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 127.0.0.1:44757         0.0.0.0:*               LISTEN      0          12721      1330/containerd     
tcp        2      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      0          232408     112960/python3      
tcp        0      0 0.0.0.0:2122            0.0.0.0:*               LISTEN      0          1908       1323/sshd: /usr/sbi 
tcp6       0      0 :::2122                 :::*                    LISTEN      0          1910       1323/sshd: /usr/sbi

**Comment by thinkst-marco** [comment]
@H20-Jenish unfortunately we're unable to assist with sslstrip issues.
