### ISSUE TITLE
json-tcp logger doesn't work under python3

### ISSUE THREAD

**Issue by amorrowbellarmine** [thinkst/opencanary#108]
I'm attempting to setup opencanary to send log events via json so they can easily be captured by my ELK server. I added the `json-tcp` config settings from [the documentation](https://opencanary.readthedocs.io/en/latest/starting/configuration.html?highlight=syslog#logger-configuration) and tried to launch `opencanaryd --dev`. It launches, but I get errors related to the json logger

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 632, in emit
    self.send(s)
  File "/home/administrator/test/lib/python3.8/site-packages/opencanary/logger.py", line 192, in send
    self.sock.sendall(s)
TypeError: a bytes-like object is required, not 'str'
Call stack:
  File "/home/administrator/test/bin/twistd", line 8, in <module>
    sys.exit(run())
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/home/administrator/test/lib/python3.8/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/home/administrator/test/bin/opencanary.tac", line 143, in <module>
    start_mod(application, klass)
  File "/home/administrator/test/bin/opencanary.tac", line 99, in start_mod
    logMsg({'logdata': msg})
  File "/home/administrator/test/bin/opencanary.tac", line 119, in logMsg
    logger.log(data, retry=False)
  File "/home/administrator/test/lib/python3.8/site-packages/opencanary/logger.py", line 161, in log
    self.logger.warn(json.dumps(logdata, sort_keys=True))
```

I googled `a bytes-like object is required, not 'str'` and found a [StackOverflow post](https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in) where someone got the same error message when moving from Python2 to Python3. It sounds like something needs to get encoded as a binary object before being passed to the socket.

I did a quick hack to `logger.py`, changed line 194 to encode the `s` variable and that fixed my issue. I'm not a python developer, but wanted to pass this along so it can be resolved properly.

Line 194 before:
`self.sock.sendall(s)`
Line 194 after:
`self.sock.sendall(s.encode())`

Server info:
OS: Ubuntu 20.04
Python: 3.8.5

**Comment by jayjb** [comment]
Hi @amorrowbellarmine,

Ah this is a good find. Ye one of the changes from python2 to python3 is the way in which it handles strings. I mustve missed it in the testing (the use of different loggers). Thanks for supplying a fix too. Ill take a look and get back to you. 

In the mean time, please send me an email `jay [at] thinkst [dot] com`. We always like to say thanks with something for folks that are helpful!

**Comment by mvl64** [comment]
It seems this issue has been resolved - the current version <Main Branch> contains this fix. You may want to close the ticket.
