### ISSUE TITLE
Error message when using NTP

### ISSUE THREAD

**Issue by swannet** [thinkst/opencanary#117]
I've setup a Open Canary Honeypot with the NTP-module (Running in docker on Ubuntu 18:04 with Python 3 in a Virtual-env).

When querying the NTP server from a Windows 10 client with: "w32tm /stripchart /computer:172.16.1.175 /dataonly /samples:5"

I got the fololow error message on the client
Tracking 172.16.1.175 [172.16.1.175:123].
Collecting 5 samples.
The current time is 15-1-2021 08:38:56.
08:38:56, error: 0x800705B4
08:38:59, error: 0x800705B4
08:39:02, error: 0x800705B4
08:39:05, error: 0x800705B4
08:39:08, error: 0x800705B4

The honeypot shows the following error in the log:

2021-01-15T07:10:58+0000 [MiniNtp (UDP)] Unhandled Error,
	Traceback (most recent call last):,
	    return context.call({ILogContext: newCtx}, func, *args, **kw),
	  File "/opt/opencanary/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext,
	  File "/opt/opencanary/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext,
	    return self.currentContext().callWithContext(ctx, func, *args, **kw),
	  File "/opt/opencanary/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext,
	    return func(*args,**kw),
	  File "/opt/opencanary/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite,
	--- <exception caught here> ---,
	    why = selectable.doRead(),
	  File "/opt/opencanary/venv/lib/python3.6/site-packages/twisted/internet/udp.py", line 249, in doRead,
	    self.protocol.datagramReceived(data, addr),
	  File "/opt/opencanary/venv/lib/python3.6/site-packages/opencanary/modules/ntp.py", line 19, in datagramReceived,
	    if len(data) < 4 or data.decode()[3]!= u'*': #monlist command,
	builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 0: invalid continuation byte

Is this a know problem or is there a work-a-round / patch I can apply?

**Comment by jayjb** [comment]
Hi @swannet,

Sorry for the delayed response. Thanks for reporting this issue. I'll take a look at a fix for it shortly and get back to you. If you would like to submit a PR, that would be awesome too.

**Comment by jayjb** [comment]
Hi @swannet,

Sorry for the delay (and subsequent stupidity), but this issue has been fixed already.
