### ISSUE TITLE
OpenCanary won't start on a Kali Raspberry Pi

### ISSUE THREAD

**Issue by syspect-tech** [thinkst/opencanary#139]
I followed directions here: https://www.paulligocki.com/open-canary-honey-pot-on-raspberry-pi/
I'm not sure how to fix this error when starting `opencanaryd --start`

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python3.9/dist-packages/Twisted-19.10.0-py3.9-linux-aarch64.egg/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/usr/local/bin/opencanary.tac", line 4, in <module>
    __import__('pkg_resources').run_script('opencanary==0.6.1', 'opencanary.tac')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 648, in run_script
    name = ns['__name__']
builtins.KeyError: '__name__'

```

Failed to load application: '__name__'

**Comment by jayjb** [comment]
Hi @syspect-tech,

Sorry for the delay on getting back to you here. Would you mind trying with the new version of OpenCanary? If it still fails, please re-open this issue and we can tackle.
