### ISSUE TITLE
Unhandled Error after successfully running for hours.

### ISSUE THREAD

**Issue by ElBiasto** [thinkst/opencanary#151]
Hey, I have two Instances of opencanary running. One on a Raspberry Pi and one on a VM.
Both show the same behaviour: After running successfully for multiple hours (sometimes even days) I run into this Error:

```
{"dst_host": "xxx.xx.20.126", "dst_port": "135", "local_time": "2021-08-21 16:34:40.367872", "local_time_adjusted": "2021-08-21 18:34:40.368017", "logdata": {"CWR": "", "DF": "", "ECE": "", "ID": "746", "IN": "eth0", "LEN": "52", "MAC": "b8:27:eb:19:c3:59:08:f1:ea:ed:d6:af:08:00:45:02:00:34:02:ea:40:00", "OUT": "", "PREC": "0x00", "PROTO": "TCP", "RES": "0x00", "SYN": "", "TOS": "0x02", "TTL": "128", "URGP": "0", "WINDOW": "8192"}, "logtype": 5001, "node_id": "0", "src_host": "xxx.xx.16.16", "src_port": "62591", "utc_time": "2021-08-21 16:34:40.367962"}
2021-08-21T18:34:40+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/internet/inotify.py", line 249, in doRead
	    fdesc.readFromFD(self._fd, self._doRead)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/internet/fdesc.py", line 94, in readFromFD
	    callback(output)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/internet/inotify.py", line 276, in _doRead
	    iwp._notify(path, mask)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-19.10.0-py2.7-linux-armv7l.egg/twisted/internet/inotify.py", line 150, in _notify
	    callback(self, filepath, events)
	  File "build/bdist.linux-armv7l/egg/opencanary/modules/__init__.py", line 169, in onChange
	    
	  File "build/bdist.linux-armv7l/egg/opencanary/modules/__init__.py", line 161, in processAuditLines
	    
	  File "build/bdist.linux-armv7l/egg/opencanary/modules/portscan.py", line 51, in handleLines
	    
	exceptions.KeyError: 'SRC'
```

I already did some research and found a post telling this could be caused by a conflict of the NTP Port. That's why I turned off NTP at the config but it ddn't help to solve the Problem. This is what my config file looks right now:

```
{
     "device.node_id": "0",
     "git.enabled": false,
     "git.port" : 9418,
     "ftp.enabled": true,
     "ftp.port": 21,
     "ftp.banner": "NAME OF THE FTP SITE YOU WANT",
     "http.banner": "Unknown",
     "http.enabled": true,
     "http.port": 80,
     "http.skin": "nasLogin",
     "httpproxy.enabled" : false,
     "httpproxy.port": 8080,
     "httpproxy.skin": "squid",
     "logger": {
         "class": "PyLogger",
         "kwargs": {
             "formatters": {
                 "plain": {
                     "format": "%(message)s"
                 },
                 "syslog_rfc": {
                     "format": "opencanaryd[%(process)-5s:%(thread)d]: %(name)s %(levelname)-5s %(message)s"
                 }
             },
             "handlers": {
                 "console": {
                     "class": "logging.StreamHandler",
                     "stream": "ext://sys.stdout"
                 },
                 "file": {
                     "class": "logging.FileHandler",
                     "filename": "/var/tmp/opencanary.log"
                 },
                 "file2": {
                     "class": "logging.FileHandler",
                     "filename": "/var/tmp/opencanary-tmp.log"
                 }
             }
         }
      },
     "portscan.enabled": true,
     "portscan.logfile":"/var/log/kern.log",
     "portscan.synrate": 5,
     "portscan.nmaposrate": 5,
     "portscan.lorate": 3,
     "smb.auditfile": "/var/log/samba-audit.log",
     "smb.enabled": false,
     "mysql.enabled": false,
     "mysql.port": 3306,
     "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
     "ssh.enabled": false,
     "ssh.port": 22,
     "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
     "redis.enabled": false,
     "redis.port": 6379,
     "rdp.enabled": true,
     "rdp.port": 3389,
     "sip.enabled": false,
     "sip.port": 5060,
     "snmp.enabled": true,
     "snmp.port": 161,
     "ntp.enabled": false,
     "ntp.port": 123,
     "tftp.enabled": true,
     "tftp.port": 69,
     "tcpbanner.maxnum":10,
     "tcpbanner.enabled": false,
     "tcpbanner_1.enabled": false,
     "tcpbanner_1.port": 8001,
     "tcpbanner_1.datareceivedbanner": "",
     "tcpbanner_1.initbanner": "",
     "tcpbanner_1.alertstring.enabled": false,
     "tcpbanner_1.alertstring": "",
     "tcpbanner_1.keep_alive.enabled": false,
     "tcpbanner_1.keep_alive_secret": "",
     "tcpbanner_1.keep_alive_probes": 11,
     "tcpbanner_1.keep_alive_interval":300,
     "tcpbanner_1.keep_alive_idle": 300,
     "telnet.enabled": false,
     "telnet.port": 23,
     "telnet.banner": "",
     "telnet.honeycreds": [
         {
             "username": "admin",
             "password": "$pbkdf2-sha512$19000$bG1NaY3xvjdGyBlj7N37Xw$dGrmBqqWa1okTCpN3QEmeo9j5DuV2u1EuVFD8Di0GxNiM64To5O/Y66f7UASvnQr8.LCzqTm6awC8Kj/aGKvwA"
         },
         {
             "username": "admin",
             "password": "admin1"
         }
     ],
     "mssql.enabled": false,
     "mssql.version": "2012",
     "mssql.port":1433,
     "vnc.enabled": true,
     "vnc.port":5000
 }
```
Does someone have any idea what the reason for the Unhandled Error could be?

**Comment by jayjb** [comment]
Hi @ElBiasto,

Thanks for reporting in (and thanks for the info). Just looking at the error it looks like the `SRC` key is missing and it is expected since thats where we get the `src_host` value from. 

There are a few ways to figure whats going wrong here:
a) we create a build that has some extra logging so that we can see what the connection/activity is that is causing this issue. Typically we expect a `SRC` key with the ip value.

b) you could check in the current logging that the OpenCanary is doing. Portscan reads a file that ip tables logs to (the default is `/var/log/kern.log`). If you grab the logs around the time that the failure occurred, we could try track down what is causing this and build some robustness.

**Comment by jayjb** [comment]
Closing issue due to lack of activity. Please re-open if you still have the same issue.
