### ISSUE TITLE
Raspberry Pi - from buster to bullseye - errors when starting opencanary

### ISSUE THREAD

**Issue by ivnmad** [thinkst/opencanary#177]
I upgraded my Raspberry Pi OS from buster to bullseye and my perfectly working opencanary [it had been working for almost 2 years]  failed to start following the upgrade.
I theretofore did a clean installation thinking that the issue had been the upgrade shortcut, but I'm getting the same error messages: 

** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
[-] Using config file: opencanary.conf
Unhandled Error
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.9/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/home/pi/env/lib/python3.9/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/home/pi/env/lib/python3.9/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/home/pi/env/lib/python3.9/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/pi/env/lib/python3.9/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/pi/env/lib/python3.9/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/home/pi/env/lib/python3.9/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/home/pi/env/bin/opencanary.tac", line 14, in <module>
    from opencanary.modules.httpproxy import HTTPProxy
  File "/home/pi/env/lib/python3.9/site-packages/opencanary/modules/httpproxy.py", line 26, in <module>
    from jinja2 import Template
  File "/home/pi/env/lib/python3.9/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/pi/env/lib/python3.9/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/home/pi/env/lib/python3.9/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/home/pi/env/lib/python3.9/site-packages/jinja2/utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
builtins.ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/pi/env/lib/python3.9/site-packages/markupsafe/__init__.py)

Failed to load application: cannot import name 'soft_unicode' from 'markupsafe' (/home/pi/env/lib/python3.9/site-packages/markupsafe/__init__.py)

Any idea on how I can solve this?

**Comment by HybridAU** [comment]
Hi @ivnmad the issue is that the latest release of MarkupSafe (which is used by Jinja2, which we use for HTTP templates) [has removed](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) `soft_unicode`.

The solution is to update Jinja2 to the latest version, there is already a [pull request that updates Jinja2](https://github.com/thinkst/opencanary/pull/175/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R16) however for you to fix your canary now before that gets merged, depending on how you have installed OpenCanary the solution will be slightly different. If you have installed it with `pip install opencanary`, the solution might be as simple as `pip install jinja2==3.0.3`

**Comment by ivnmad** [comment]
@HybridAU I had installed using pip, so `pip install jinja2==3.0.3 `solved the issue. Thank you.
