### ISSUE TITLE
opencanary.tac not coping correctly

### ISSUE THREAD

**Issue by HybridAU** [thinkst/opencanary#34]
When I run `python setup.py install` the `opencanary.tac` file doesn't seem to copy across to the `bin` folder. I'm not really sure what's happening but I think it might be setuptools trying to do something fancy like trying to compile it and then link to the compiled .pyc file. 

When I look at `~/env/bin/opencanary.tac` it contains 

```
#!/home/pi/canary-env/bin/python
# EASY-INSTALL-SCRIPT: 'opencanary==0.3.2','opencanary.tac'
__requires__ = 'opencanary==0.3.2'
__import__('pkg_resources').run_script('opencanary==0.3.2', 'opencanary.tac')
```

and running `opencanaryd --start` results in

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-14.0.2-py2.7-linux-armv7l.egg/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/local/bin/opencanary.tac", line 4, in <module>
    __import__('pkg_resources').run_script('opencanary==0.3.2', 'opencanary.tac')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 531, in run_script
    name = ns['__name__']
exceptions.KeyError: '__name__'

Failed to load application: '__name__'
```

Simply running `cp bin/opencanary.tac ~/env/bin/opencanary.tac` after installing fixes the issue.

**Comment by chriswhitehat** [comment]
This looks like an environment/path problem, if you run the same requires/import via an interactive shell for instance it is successful without copying the file over.

I'm less familiar with distribution tools and setuptools based script execution so I haven't enumerated a fix just yet.

**Comment by thinkst** [comment]
Hey @HybridAU,

Thanks for finding this (I have also bumped into this!). I will look for a better fix, but for the meantime, I am going to reference your fix on the frontage (Thanks so much!).

**Comment by thinkst** [comment]
Hey @HybridAU,

We have found that there may be an issue with setup_tools. If you want to build from the repo instead of using `pip install opencanary`, you may a different approach that we have found to work. Once you have cloned the OpenCanary git  repo and setup your virtual env and activated it, you can run,
`python setup.py sdist`. 

This will create a `opencanary-<version>.tar.gz` inside the `dist` folder. You may then run, 
`pip install opencanary-<version>.tar.gz`

You should know be able to run opencanaryd as usual, but built from the source repo.
