### ISSUE TITLE
Failure to run on Redhat/CentOS 7 - Failed to load application: '__name__'

### ISSUE THREAD

**Issue by camAtGitHub** [thinkst/opencanary#36]
Performing the following on a clean install of Rehat 7:
```
yum install git gcc make python-devel python2-pip python-virtualenv
virtualenv env/
. env/bin/activate
pip install opencanary
pip install scapy pcapy
git clone https://github.com/thinkst/opencanary
cd opencanary/
python setup.py install
opencanaryd --copyconfig
opencanaryd --start
```
Produces the following error message:

```
(env)[root@camtest1 ~]# opencanaryd --start
Unhandled Error
Traceback (most recent call last):
  File "/root/env/lib/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/root/env/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/root/env/lib/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/root/env/lib/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/root/env/lib/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/root/env/lib/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/root/env/lib/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/root/env/bin/opencanary.tac", line 5, in <module>
    pkg_resources.run_script('opencanary==0.3.2', 'opencanary.tac')
  File "/root/env/lib/python2.7/site-packages/pkg_resources.py", line 537, in run_script
    name = ns['__name__']
exceptions.KeyError: '__name__'

Failed to load application: '__name__'
```
Any help would be appreciated

**Comment by thinkst** [comment]
Hey @camAtGitHub,

We have found that there may be an issue with setup_tools. If you want to build from the repo instead of using `pip install opencanary`, you may a different approach that we have found to work. Once you have cloned the OpenCanary git  repo and setup your virtual env and activated it, you can run,
`python setup.py sdist`. 

This will create a `opencanary-<version>.tar.gz` inside the `dist` folder. You may then run, 
`pip install opencanary-<version>.tar.gz`

You should know be able to run opencanaryd as usual, but built from the source repo.
