### ISSUE TITLE
[BUG] getpwnam(): name not found: 'opencanary' after upgrade to 0.9.4

### ISSUE THREAD

**Issue by 72tlukas72** [thinkst/opencanary#377]
After upgrade container from 0.9.3 to 0.9.4 have some errors and container doesn't start.

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 254, in parseOptions

    self._dispatch[optMangled].dispatch(optMangled, arg)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 59, in dispatch

    value = self.coerce(value)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 866, in uidFromString

    return pwd.getpwnam(uidString)[2]

KeyError: "getpwnam(): name not found: 'opencanary'"

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 862, in uidFromString

    return int(uidString)

ValueError: invalid literal for int() with base 10: 'opencanary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/bin/twistd", line 8, in <module>

    sys.exit(run())

  File "/usr/local/lib/python3.10/site-packages/twisted/scripts/twistd.py", line 35, in run

    app.run(runApp, ServerOptions)

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 668, in run

    config.parseOptions()

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 635, in parseOptions

    usage.Options.parseOptions(self, options)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 254, in parseOptions

    self._dispatch[optMangled].dispatch(optMangled, arg)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 59, in dispatch

    value = self.coerce(value)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 866, in uidFromString

    return pwd.getpwnam(uidString)[2]

KeyError: "getpwnam(): name not found: 'opencanary'"

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 862, in uidFromString

    return int(uidString)

ValueError: invalid literal for int() with base 10: 'opencanary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/bin/twistd", line 8, in <module>

    sys.exit(run())

  File "/usr/local/lib/python3.10/site-packages/twisted/scripts/twistd.py", line 35, in run

    app.run(runApp, ServerOptions)

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 668, in run

    config.parseOptions()

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 635, in parseOptions

    usage.Options.parseOptions(self, options)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 254, in parseOptions

    self._dispatch[optMangled].dispatch(optMangled, arg)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 59, in dispatch

    value = self.coerce(value)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 866, in uidFromString

    return pwd.getpwnam(uidString)[2]

KeyError: "getpwnam(): name not found: 'opencanary'"

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 862, in uidFromString

    return int(uidString)

ValueError: invalid literal for int() with base 10: 'opencanary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/bin/twistd", line 8, in <module>

    sys.exit(run())

  File "/usr/local/lib/python3.10/site-packages/twisted/scripts/twistd.py", line 35, in run

    app.run(runApp, ServerOptions)

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 668, in run

    config.parseOptions()

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 635, in parseOptions

    usage.Options.parseOptions(self, options)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 254, in parseOptions

    self._dispatch[optMangled].dispatch(optMangled, arg)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 59, in dispatch

    value = self.coerce(value)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 866, in uidFromString

    return pwd.getpwnam(uidString)[2]

KeyError: "getpwnam(): name not found: 'opencanary'"

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 862, in uidFromString

    return int(uidString)

ValueError: invalid literal for int() with base 10: 'opencanary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/bin/twistd", line 8, in <module>

    sys.exit(run())

  File "/usr/local/lib/python3.10/site-packages/twisted/scripts/twistd.py", line 35, in run

    app.run(runApp, ServerOptions)

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 668, in run

    config.parseOptions()

  File "/usr/local/lib/python3.10/site-packages/twisted/application/app.py", line 635, in parseOptions

    usage.Options.parseOptions(self, options)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 254, in parseOptions

    self._dispatch[optMangled].dispatch(optMangled, arg)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/usage.py", line 59, in dispatch

    value = self.coerce(value)

  File "/usr/local/lib/python3.10/site-packages/twisted/python/util.py", line 866, in uidFromString

    return pwd.getpwnam(uidString)[2]

KeyError: "getpwnam(): name not found: 'opencanary'"

**Comment by thinkst-az** [comment]
Thanks @72tlukas72, we're on this. (It's related to the recent change to drop root privileges by default.)

**Comment by thinkst-az** [comment]
Thanks again @72tlukas72, we've fixed this in v0.9.5

**Comment by Taomyn** [comment]
How do I get the fix? I've tried the same command as I used for upgrading to 0.9.4 but it says there's no change:
```
[root@frink ~]# . env/bin/activate
(env) [root@frink ~]# pip install opencanary -U
Requirement already satisfied: opencanary in ./env/lib/python3.12/site-packages (0.9.4)
Requirement already satisfied: Twisted==22.8.0 in ./env/lib/python3.12/site-packages (from opencanary) (22.8.0)
Requirement already satisfied: pyasn1==0.4.5 in ./env/lib/python3.12/site-packages (from opencanary) (0.4.5)
Requirement already satisfied: cryptography==38.0.1 in ./env/lib64/python3.12/site-packages (from opencanary) (38.0.1)
Requirement already satisfied: simplejson==3.16.0 in ./env/lib64/python3.12/site-packages (from opencanary) (3.16.0)
Requirement already satisfied: requests==2.31.0 in ./env/lib/python3.12/site-packages (from opencanary) (2.31.0)
Requirement already satisfied: zope.interface==5.0.0 in ./env/lib64/python3.12/site-packages (from opencanary) (5.0.0)
Requirement already satisfied: PyPDF2==1.26.0 in ./env/lib/python3.12/site-packages (from opencanary) (1.26.0)
Requirement already satisfied: fpdf==1.7.2 in ./env/lib/python3.12/site-packages (from opencanary) (1.7.2)
Requirement already satisfied: passlib==1.7.1 in ./env/lib/python3.12/site-packages (from opencanary) (1.7.1)
Requirement already satisfied: Jinja2==3.0.1 in ./env/lib/python3.12/site-packages (from opencanary) (3.0.1)
Requirement already satisfied: ntlmlib==0.72 in ./env/lib/python3.12/site-packages (from opencanary) (0.72)
Requirement already satisfied: bcrypt==3.1.7 in ./env/lib64/python3.12/site-packages (from opencanary) (3.1.7)
Requirement already satisfied: setuptools==68.0.0 in ./env/lib/python3.12/site-packages (from opencanary) (68.0.0)
Requirement already satisfied: urllib3==2.0.7 in ./env/lib/python3.12/site-packages (from opencanary) (2.0.7)
Requirement already satisfied: hpfeeds==3.0.0 in ./env/lib/python3.12/site-packages (from opencanary) (3.0.0)
Requirement already satisfied: pyOpenSSL==22.1.0 in ./env/lib/python3.12/site-packages (from opencanary) (22.1.0)
Requirement already satisfied: service-identity==21.1.0 in ./env/lib/python3.12/site-packages (from opencanary) (21.1.0)
Requirement already satisfied: cffi>=1.1 in ./env/lib64/python3.12/site-packages (from bcrypt==3.1.7->opencanary) (1.16.0)
Requirement already satisfied: six>=1.4.1 in ./env/lib/python3.12/site-packages (from bcrypt==3.1.7->opencanary) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib64/python3.12/site-packages (from Jinja2==3.0.1->opencanary) (2.1.5)
Requirement already satisfied: ordereddict in ./env/lib/python3.12/site-packages (from ntlmlib==0.72->opencanary) (1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./env/lib64/python3.12/site-packages (from requests==2.31.0->opencanary) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.12/site-packages (from requests==2.31.0->opencanary) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.12/site-packages (from requests==2.31.0->opencanary) (2024.2.2)
Requirement already satisfied: attrs>=19.1.0 in ./env/lib/python3.12/site-packages (from service-identity==21.1.0->opencanary) (23.2.0)
Requirement already satisfied: pyasn1-modules in ./env/lib/python3.12/site-packages (from service-identity==21.1.0->opencanary) (0.2.5)
Requirement already satisfied: constantly>=15.1 in ./env/lib/python3.12/site-packages (from Twisted==22.8.0->opencanary) (23.10.4)
Requirement already satisfied: incremental>=21.3.0 in ./env/lib/python3.12/site-packages (from Twisted==22.8.0->opencanary) (22.10.0)
Requirement already satisfied: Automat>=0.8.0 in ./env/lib/python3.12/site-packages (from Twisted==22.8.0->opencanary) (22.10.0)
Requirement already satisfied: hyperlink>=17.1.1 in ./env/lib/python3.12/site-packages (from Twisted==22.8.0->opencanary) (21.0.0)
Requirement already satisfied: typing-extensions>=3.6.5 in ./env/lib/python3.12/site-packages (from Twisted==22.8.0->opencanary) (4.10.0)
Requirement already satisfied: pycparser in ./env/lib/python3.12/site-packages (from cffi>=1.1->bcrypt==3.1.7->opencanary) (2.21)
(env) [root@frink ~]#
```

**Comment by 72tlukas72** [comment]
I can confirm it is fixed in 0.9.5. Thank you.

**Comment by thinkst-az** [comment]
@Taomyn : Please could you try again? I messaged here by mistake before completing the v0.9.5 upgrade on PyPI.

**Comment by Taomyn** [comment]
> @Taomyn : Please could you try again? I messaged here by mistake before completing the v0.9.5 upgrade on PyPI.

Thanks, it's working now
